### ISSUE TITLE
Ansible Pack Install Fails in container 

### ISSUE THREAD

**Issue by SimplySeth** [StackStorm/st2-docker#104]
Ansible Pack Install Fails in container because of missing `libkrb5-dev` package. 

Fix ... 

```
sudo docker exec -it  <id of container>  "/bin/bash"

apt-get update && apt -y install libkrb5-dev

exit
```
Then re-run the ansible pack install via the WebUI

**Comment by warrenvw** [comment]
Hi @SimplySeth. Yes, that is one way to do it.

You could use `entrypoint.d` to satisfy the requirements using an existing image, or you could add to the Dockerfile and rebuild. Obviously, baking everything into the image will result in faster startup times, and provide a more consistent execution if you're starting multiple containers based on the image...

**Comment by SimplySeth** [comment]
... well at least this might help someone. Thanks for the reply, it is greatly appreciated.

**Comment by warrenvw** [comment]
I'll update the README with this info as it has been raised a few times now. Thanks!
