### ISSUE TITLE
how to predefine the Sharing code between Sensors and Python Actions

### ISSUE THREAD

**Issue by NikosVlagoidis** [StackStorm/st2-docker#105]
In the [this](https://docs.stackstorm.com/reference/sharing_code_sensors_actions.html#sharing-code-between-sensors-and-python-actions) section of the documentation, we can see that you can share code through a lib folder but you need to enable it on /etc/st2/st2.conf.
How can I do that with docker before I start the container? How can I be sure that the settings will remain the same if the container goes down?

**Comment by LindsayHill** [comment]
My guess would be to do something like [this](https://github.com/StackStorm/st2-docker#st2-dockerentrypointd)

So you'd end up with a script that did this:
```shell
#/bin/bash
crudini --set /etc/st2/st2.conf packs enable_common_libs 'True'
```

**Comment by NikosVlagoidis** [comment]
You actually answer it on Slack too! Thank you again 👍
