### ISSUE TITLE
Configure the coordination backend

### ISSUE THREAD

**Issue by warrenvw** [StackStorm/st2-docker#11]
The following log entry was seen in st2api.log:

```
2017-04-27 19:36:15,425 139761017480048 WARNING coordination [-] Coordination backend is not configured. Code paths which use coordination service will use best effort approach and race conditions are possible.
```

Yuck.

**Comment by warrenvw** [comment]
After adding:

```
[coordination]
url = redis://redis-pass@redis:6379
```

to `/etc/st2/st2.conf`, the WARNING disappears, but I now see the following error in `st2notifier.log`:

```
st2notifier.log:  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/tooz/drivers/redis.py", line 28, in <module>
st2notifier.log:    import redis
st2notifier.log:ImportError: No module named redis
```

**Comment by warrenvw** [comment]
See https://docs.stackstorm.com/reference/policies.html

Some of these coordination backends also require corresponding client libraries to be installed in StackStorm virtualenv. We do not ship these libraries by default. As an example, to install the client library in StackStorm virtualenv, run

> `sudo su`
> `source /opt/stackstorm/st2/bin/activate`
> `pip install redis`

**Comment by m4dcoder** [comment]
IS concurrency policy on a StackStorm action tested w/ this new setup?

**Comment by warrenvw** [comment]
Yes, as of 9c76308c51d42f6f27faea315e601d8441cffbd6.

**Comment by Deepika-Kamalla** [comment]
Does st2.conf file support adding redundant pairs of backend coordinator like zookeeper or redis?
We have zookeeper cluster (3 instances) but not sure how to include 3 instances in st2.conf.
Tried below config but doesn't work.

[coordination]
url = kazoo://user:pass@host1:2181/,
      kazoo://user:pass@host2:2181/,
      kazoo://user:pass@host3:2181/
