### ISSUE TITLE
Tuts for chatops

### ISSUE THREAD

**Issue by saurav-terraform** [StackStorm/st2-docker#114]
The details for the chatops tuts will be helpful

**Comment by bigmstone** [comment]
@saurav-terraform could you provide more information? I'm not sure what exactly you're asking.

**Comment by dev-head** [comment]
he's looking for tutorial to enable chatops via this docker installation.

**Comment by LindsayHill** [comment]
The basic setup is now covered in the [README](
https://github.com/StackStorm/st2-docker#to-enable-chatops)

Further ChatOps documentation is in docs.stackstorm.com/chatops/index.html
