### ISSUE TITLE
Configurable Helm chart for StackStorm Kubernetes

### ISSUE THREAD

**Issue by jdotjdot** [StackStorm/st2-docker#119]
It's fantastic that there are both docker and Kubernetes configurations available for Stackstorm, but for Kubernetes in particular, I think it would be easiest to get greater adoption if there were a Helm chart readily available.  It can be tough to manage applications using just `kubectl apply`, and most companies that I know of that are using Kubernetes seriously are using Helm for it.

**Comment by jbrownsc** [comment]
We have a few in-progress, but none have comprehensively done this yet. 

https://github.com/jbrownsc/st2-docker/tree/helm_example_jbrownsm/runtime/kubernetes-1ppc/helm
https://github.com/longfei-zhang/helm-for-stackstorm

If you have any particular configuration of Stack Storm you want to see represented, let us know.  I think the first goal would be the HA architecture (https://docs.stackstorm.com/reference/ha.html) would be represented.

**Comment by jbrownsc** [comment]
Some thoughts from my perspective

_Goals for helm chart_
- Be able to deploy a brand new Stack Storm service in 5 minutes on any Kubernetes cluster that helm >2.8.0 is installed on.
- Be able to manage a "production" Stack Storm service using helm where all upgrades are handled by helm with little to no downtime

_Must have Service Architecture_
- 1 Pod per Stack Storm service
- Configurable number of replicas for all st2* + mistral* services (default of 2)
- Utilize existing Ingress or create new ingress configuration
- Default Limits for MongoDB, Postgres, RabbitMQ, and Redis
- Tunable sizes for persistent volumes
- Shared storage OR Pre-baked container model, for packs
- Mongo Replicaset or Mongo Standalone or no Mongo at all
- st2.conf should be configurable via helm values (override mongodb to external mongo server for example)
- secret management? (Not sure the best way for this, vault, helm-secrets, other?)
- Bootstrap job for brand new installations (optional if you're restoring from a backup)
- Upgrade job for "register-all" and any other upgrade related operations (Mistral migrations?)
- Health checks for all st2 services (liveness + readiness)
- Support standard definitions (nodeSelector, tolerations, annotations, resources)
- Ability to NOT provision external services like Mongo, Postgres, Redis, Rabbitmq (services exist outside of Helm chart definition)

_Nice to have Service Architecture_
- Postgres HA?
- RabbitMQ cluster?
- Redis cluster?

**Comment by jbrownsc** [comment]
@jdotjdot We have a couple approaches here.  Are your actions + rules encapsulated in a pack?  Or would you be thinking development purposes?

**Comment by jdotjdot** [comment]
We've put them in a small private pack just for organizational purposes, but it's really just a collection of internal scripts for ourselves.

**Comment by armab** [comment]
Superseded by https://docs.stackstorm.com/install/k8s_ha.html and https://github.com/stackstorm/stackstorm-ha Helm chart.

Thanks everyone, this discussion and well structured plan breakdown https://github.com/StackStorm/st2-docker/issues/119#issuecomment-386374326 really helped us during the ST2 HA Helm chart development.
