### ISSUE TITLE
Cannot retrieve GPG key when building stackstorm image

### ISSUE THREAD

**Issue by pkaramol** [StackStorm/st2-docker#135]
**Describe the problem**
In the effort to build just the `stackstorm` image:

- Clone/download the entire project
- `cd /images/stackstorm`
- `docker build --tag somereponame:st2-docker-test .`

__ERROR__

```
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.Ijqg236RMp --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver keyserver.ubuntu.com --recv-keys ABF5BD827BD9BF62
gpg: requesting key 7BD9BF62 from hkp server keyserver.ubuntu.com
gpgkeys: key ABF5BD827BD9BF62 can't be retrieved
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
The command '/bin/sh -c wget -O - http://nginx.org/keys/nginx_signing.key | apt-key add -     && echo "deb http://nginx.org/packages/mainline/ubuntu/ trusty nginx" >> /etc/apt/sources.list     && echo "deb-src http://nginx.org/packages/mainline/ubuntu/ trusty nginx" >> /etc/apt/sources.list     && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ABF5BD827BD9BF62     && apt-get update     && apt-get install -y nginx     && cp /usr/share/doc/st2/conf/nginx/st2.conf /etc/nginx/conf.d/st2-base.cnf     && ( cd /etc/nginx/conf.d && ln -s st2-base.cnf st2.conf )     && mkdir -p /etc/ssl/st2     && mkdir /var/run/sshd     && openssl req -x509 -newkey rsa:2048 -keyout /etc/ssl/st2/st2.key -out /etc/ssl/st2/st2.crt -days 3650 -nodes -subj '/O=st2 self signed/CN=localhost'' returned a non-zero code: 2
```

**Versions**
 - Host OS: Ubuntu 16.04
 - docker: 18.03.1-ce
 - docker-compose: 1.16.1, build 6d1ac21
 - stackstorm/stackstorm image:N/A

**To Reproduce**
Check above

**Comment by mbayha** [comment]
We ran into the same issue. Turned out that the issue was that port 11371 was blocked by our firewall. 

We updated line 120 in Dockerfile and changed `--keyserver keyserver.ubuntu.com` to `--keyserver hkp://keyserver.ubuntu.com:80`

Found the solution at [https://superuser.com/questions/64922/how-to-work-around-blocked-outbound-hkp-port-for-apt-keys](https://superuser.com/questions/64922/how-to-work-around-blocked-outbound-hkp-port-for-apt-keys)

**Comment by armab** [comment]
Thanks for reporting a possible solution!
Can you submit a PR with that enhancement?

**Comment by blag** [comment]
My PR #137 does this instead:

```diff
-    && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ABF5BD827BD9BF62 \
-    && apt-get update \
+    && ( \
+        apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ABF5BD827BD9BF62 \
+        || \
+        apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys ABF5BD827BD9BF62 \
+    ) && apt-get update \
```

**Comment by blag** [comment]
@armab I'll let you pick which PR you want to merge.

**Comment by blag** [comment]
armab noticed that we are already importing the key with wget (first line of that `RUN` directive), so I moved the `apt-key` line up there and simplified it to use the `hkp://...:80` method regardless.
