### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by zhoushuai0207** [StackStorm/st2-docker#139]
**Describe the problem**
A clear and concise description of what the problem is.

**Versions**
 - Host OS: [ centos7 ]
 - docker: [18.05.0-ce]
 - docker-compose: [3.3.0]
 - stackstorm/stackstorm image: [latest]

Through the UI, click on the create icon ,Jump to
https://192.168.242.xxx/undefined/#/import/eyJhdXRoIjp0cnVlLCJ0b2tlbiI6eyJzZXJ2aWNlIjpmYWxzZSwiZXhwaXJ5IjoiMjAxOC0wNS0yOVQyMDoxNDoyOC41MDEyNzFaIiwidG9rZW4iOiJmMzgzOTRmMDJmMDM0ODNjOGQ4ZjE3MWM2MTU1OTc2YyIsInVzZXIiOiJzdDJhZG1pbiIsImlkIjoiNWIwYzYzMjRiNDZmMTQwMTAxZjI3YTc4IiwibWV0YWRhdGEiOnt9fX0, What "undefined"?

**Comment by armab** [comment]
I believe similar case reported in https://github.com/StackStorm/st2web/issues/487

If that's your issue, - please write a few messages there. That'll give bug more priority.
