### ISSUE TITLE
Stackstorm in docker swarm

### ISSUE THREAD

**Issue by miguelconde91** [StackStorm/st2-docker#144]
I want to deploy stackstorm in a docker swarm using docker stack deploy -c ./docker-compose.yml stackstorm, however:
failed to create service stackstorm_redis: Error response from daemon: The network stackstorm_private cannot be used with services. Only networks scoped to the swarm can be used, such as those created with the overlay driver.

ok, Now when I change network driver to overlay:
networks:
  public:
    driver: overlay
  private:
    driver: overlay

The result is:
Creating network stackstorm_private
Creating network stackstorm_public
Creating service stackstorm_redis
Creating service stackstorm_stackstorm
Creating service stackstorm_mongo
Creating service stackstorm_rabbitmq
Creating service stackstorm_postgres

All the services are created, however stackstorm_stackstorm never start, I can not see any log, any idea about a good deploy mechanism to stackstorm over docker swarm?

**Versions**
 - Host OS: Ubuntu 16.04
 - docker: Docker version 18.06.0-ce, build 0ffa825
 - docker-compose: I no have
 - stackstorm/stackstorm image: latest

**Comment by warrenvw** [comment]
After changing the driver from `bridge` to `overlay`, I executed

```
$ docker stack deploy -c ./docker-compose.yml stackstorm
```

As you reported, the `stackstorm` container did not start. I noticed the following helpful line in `/var/log/syslog`:

```
Oct 26 04:20:56 localhost dockerd[4157]: time="2018-10-26T04:20:56.310704010Z"
level=error msg="fatal task error" error="invalid mount config for type \"bind\":
bind mount source path does not exist: /st2-docker/packs.dev"
module=node/agent/taskmanager node.id=nq3r050jxhunkhclvpt9jy1ht 
service.id=qm7zli459ph3aac1u49mtceh8 task.id=z56pllvjnem2y99o9k6p5idxk
```

Once I removed the following line from `docker-compose.yml`, and deployed the stack a second time, the container started successfully:

```
      - ./packs.dev:/opt/stackstorm/packs.dev
```

**Comment by warrenvw** [comment]
Closing this issue. Please re-open if there's anything to add.
