### ISSUE TITLE
Adding proxy support in kubernetes-1ppc

### ISSUE THREAD

**Issue by skbly7** [StackStorm/st2-docker#154]
**Is your feature request related to a problem? Please describe.**
Kubernetes configurations don't have placeholder or information page to run behind web proxy. This is especially more tiresome to debug given few hosts like st2web, st2auth, etc need to be connected without proxy.

**Describe the solution you'd like**
Proxy variables (`HTTP_PROXY`, `HTTPS_PROXY`, `NO_PROXY`) placeholder as a configmap

**Describe alternatives you've considered**
Manual instructions as documentation to do so

**Comment by warrenvw** [comment]
Hello @skbly7. `kubernetes-1ppc` is deprecated and will be removed early next year, in favor of the official `stackstorm-ha` helm chart available at https://helm.stackstorm.com. If st2web service type of LoadBalancer does not meet your requirements, please open another issue in the https://github.com/stackstorm/stackstorm-ha repository.

With the above in mind, I'll close this issue.
