### ISSUE TITLE
st2 inquiry {list,get,respond} uses ST2_BASE_URL (compose-1ppc)

### ISSUE THREAD

**Issue by trstruth** [StackStorm/st2-docker#157]
**Describe the problem**
typing `st2 inquiry list` in the st2client container will fail with `Failed to establish a new connection: [Errno 111] Connection refused`.  By using the `--debug` flag we can see that inquiries use the `ST2_BASE_URL` to construct the corresponding request.

All of the other cli commands use ST2_API_URL.  I wouldn't say this behavior is _wrong_ but I think it is unexpected.  One potential fix is to add `ST2_BASE_URL=http://st2api` in [common.env](https://github.com/StackStorm/st2-docker/blob/master/runtime/compose-1ppc/common.env).  But I'm not sure if the base url is used in other places which may be broken by this.  Another potential fix might be to dig into why cli inquiry uses a different url as the other cli commands, and fix it in the cli source code.

**Versions**
 - Host OS: Ubuntu 14.04
 - docker: 18.06.1-ce
 - docker-compose: 1.22.0
 - stackstorm/stackstorm image: st2 2.9.1, on Python 2.7.6

**To Reproduce**
Follow the README in [compose-1ppc](https://github.com/StackStorm/st2-docker/tree/master/runtime/compose-1ppc) then execute st2 inquiry list in a container other than st2api

**Comment by warrenvw** [comment]
Hi @trstruth. Thanks for reporting this.

This is not an issue with `st2-docker` itself. It's a combination of inquiries using the `/exp` URL, and st2client not handling that.

See https://github.com/StackStorm/st2/pull/4212 and https://github.com/StackStorm/st2/issues/4186.

We expect to have this resolved in StackStorm 3.1.

With the above in mind, I'll close this issue now. Please feel free to re-open if necessary.

**Comment by trstruth** [comment]
@warrenvw should've searched for this issue in the existing ones first, thanks for cleaning this up.
