### ISSUE TITLE
Error - missing the conf/environment files

### ISSUE THREAD

**Issue by djh2020** [StackStorm/st2-docker#16]
The env files specified in the docker-compose.yml are not present

env_file:
      - conf/stackstorm.env
      - conf/mongo.env
      - conf/rabbitmq.env
      - conf/postgres.env

**Comment by warrenvw** [comment]
@djh2020 Thanks for the report!

I opened a PR regarding this earlier today. Please see https://github.com/StackStorm/st2-docker/pull/15. I expect to merge later today. Please try it out and let me know if there are any issues with it.

**Comment by warrenvw** [comment]
I've merged #15 to master. These files are now created when you run `make env`. See the updated `README.md`.
