### ISSUE TITLE
St2chatops service does not read from environment variables

### ISSUE THREAD

**Issue by sahilsk** [StackStorm/st2-docker#163]
**Describe the problem**

st2chatops service not honoring environment variables.

** Reproduce **
- have hubot enviornment variables set in docker-compose file using env-file
- login inside container and empty `chatops/st2chatops.env` file.
- ConfirmEnvironment variables are set: 
```
root@8708d935768e:/opt/stackstorm# echo $HUBOT_ADAPTER
slack
```
- start chatops service  `sudo service st2chatops restart`

** Error **

tail -f /var/log/st2/st2chatops.log
```
Must provide HUBOT_ADAPTER ENV variable to start.
See README.md for more information
Must provide HUBOT_ADAPTER ENV variable to start.
```

**Comment by lingfish** [comment]
Agreed, same for me.  I've had to use bind mount, but this issue means I can't set things like `webui_base_url`.
