### ISSUE TITLE
Executions stuck in a "requested" state (compose-1ppc)

### ISSUE THREAD

**Issue by trstruth** [StackStorm/st2-docker#166]
**Describe the problem**
After a clean bring up of compose-1ppc, all executions do not proceed - and are stuck in a requested state.

**Versions**
 - Host OS: Ubuntu 16.04
 - docker: 18.09.0, build 4d60db4
 - docker-compose: docker-compose version 1.23.2, build 1110ad0
 - stackstorm/stackstorm image: 2.10.0

**To Reproduce**
start with a fresh ubuntu 16.04 environment

clone the repository and generate conf files
`git clone https://github.com/StackStorm/st2-docker.git && cd st2-docker`
`make env`
`cd runtime/compose-1ppc`
`cp -r ../../conf .`

bring up containers
`docker-compose up -d`

register inital content
`docker-compose exec st2actionrunner st2-register-content --config-file /etc/st2/st2.conf --register-all --register-setup-virtualenvs`

enter st2client container and run simple action
`docker exec -it compose-1ppc_st2client_1 bash`
`st2 run core.local cmd=date`

This action will never complete, and with `st2 execution list` one can see that this execution is stuck in a requested state.  

![image](https://user-images.githubusercontent.com/9982381/50254378-afc4b400-03a2-11e9-97af-fd056b86da8a.png)

Please let me know if this can be successfully repro'd, and if I need to provide further information.

**Comment by shusugmt** [comment]
Note: 1ppc is deprecated in favor of
https://github.com/StackStorm/stackstorm-ha

This is because 1ppc image does not include st2scheduler added in 2.10. Fix
is straightforward and easy. Are you willing to open a PR?

-- 
-- 
Shu Sugimoto

**Comment by trstruth** [comment]
Yes, I'll give it a try
