### ISSUE TITLE
console is not able to login

### ISSUE THREAD

**Issue by babujii** [StackStorm/st2-docker#169]
Given the below credentials is using.i am not able to login .  Is it correct one?

ST2_USER=st2admin
ST2_PASSWORD=IuiOavqB

**Comment by warrenvw** [comment]
Hello @babujii. I presume you are trying to access the stackstorm container. If so, per https://github.com/stackstorm/st2-docker#tldr, you should be able to run `docker-compose exec stackstorm bash` to gain access. No login required.

**Comment by warrenvw** [comment]
Closing this issue. Please re-open if necessary.
