### ISSUE TITLE
SSL Certificates not taken into account by stackstorm

### ISSUE THREAD

**Issue by pkaramol** [StackStorm/st2-docker#170]
**Describe the problem**
I am trying to run `st2-docker` in via compose.

I am using a custom packs index by appending to `/etc/st2/st2.conf`

```
[content]
packs_base_paths = /opt/stackstorm/packs.custom
index_url = https://my.local.gitlab/api/v4/projects/635/repository/files/v1%2Findex.json/raw?private_token=sometoken&ref=master
```

However the index health fails with `ssl` error

**https://localhost/api/v1/packs/index/health**

```
{
    "packs": {
        "count": 0
    },
    "indexes": {
        "count": 1,
        "status": [
            {
                "url": "https://my.local.gitlab/api/v4/projects/635/repository/files/v1%2Findex.json/raw?private_token=sometoken&ref=master",
                "message": "SSLError(SSLError(SSLError(\"bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)\",),),)",
                "error": "unresponsive",
                "packs": 0
            }
        ],
        "valid": 0,
        "errors": {
            "unresponsive": 1
        },
        "invalid": 1
    }
}

I have installed our custom certificates and the following command has exit code `0`.

`openssl s_client -connect my.local.gitlab:443 -CApath /usr/local/share/ca-certificates/`

I have also tried to added as environmental variable to `docker-compose` for the `st2` service the following

`REQUESTS_CA_BUNDLE: /usr/local/share/ca-certificates
`

Any suggestions?

````
**Versions**
 - Host OS: containerized
 - docker: `18.0.9`
 - docker-compose: `1.23.2, build 1110ad01`
 - stackstorm/stackstorm image: `v2.10.2`

**Comment by pkaramol** [comment]
The problem was addressed by adding to `st2api-default.conf`

`REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt`

but why doesn't the image respect the environmental variables passed directly to the container?

**Comment by warrenvw** [comment]
Within the default `stackstorm` container, all st2 services are started by the init process, which doesn't pass along env vars. This is more properly handled by 1 process per container solutions such as `compose-1ppc` or `stackstorm-ha` (https://github.com/StackStorm/stackstorm-ha) which do not use init.

**Comment by warrenvw** [comment]
Please re-open this issue if necessary.

**Comment by Sphinxs** [comment]
Is there an option to disable the certificates?
