### ISSUE TITLE
Not able to mount PVC 

### ISSUE THREAD

**Issue by diyaachar** [StackStorm/st2-docker#172]
**Describe the problem**
I'm running Stackstorm as a pod in a kubernetes cluster. I'm trying to mount a PVC to the path, /opt/stackstorm. When I mount the PVC to this point, none of the files are available. It is blank.
I'm using Stackstorm image tagged, 2.6.0. There is no Dockerfile available on your GitHub page for this version. 
If a PVC is mounted to /opt/stackstorm/configs, it is working as expected. If a PVC is not mounted it works fine.

Can you please let me know the volume mount point or how I can fix this issue? 

**To Reproduce**
1. Bring up Stackstorm and the necessary tools as separate pods in a k8s cluster.
2.  Mount a PVC to /opt/stackstorm.
3. Get into the stackstorm pod and check the mount point.

**Comment by LindsayHill** [comment]
Why are you using such an old version of ST2? 2.10 is the current version.

If you're running on k8s, you should look at our helm charts at https://github.com/StackStorm/stackstorm-ha

**Comment by warrenvw** [comment]
Closing this issue. Please re-open if necessary.
