### ISSUE TITLE
HTTP 503 - Running st2 run tutorial.hello

### ISSUE THREAD

**Issue by jalbertodin** [StackStorm/st2-docker#177]
**Describe the problem**
When trying to run st2 run tutorial.hello, I got the following message:

root@048f5cda7faf:/# st2 run tutorial.hello
Failed to authenticate with credentials provided in the config.
ERROR: 503 Server Error: Service Unavailable
Unable to retrieve detailed message from the HTTP response. Expecting value: line 1 column 1 (char 0)
 for url: http://127.0.0.1:9100/tokens

The port is liten
root@048f5cda7faf:/# netstat -na | grep 9100
tcp        0      0 127.0.0.1:9100          0.0.0.0:*               LISTEN

root@048f5cda7faf:/# st2ctl status
##### st2 components status #####
st2actionrunner PID: 2463
st2actionrunner PID: 2466
st2actionrunner PID: 2469
st2actionrunner PID: 2472
st2api PID: 2484
st2api PID: 2526
st2stream PID: 2544
st2stream PID: 2564
st2auth PID: 2575
st2auth PID: 2590
st2garbagecollector PID: 2600
st2notifier PID: 2607
st2resultstracker PID: 2617
st2rulesengine PID: 2625
st2sensorcontainer PID: 2632
st2chatops is not running.
st2timersengine PID: 2659
st2workflowengine PID: 2680
st2scheduler PID: 2697
mistral-server is not running.
mistral.api is not running.

**Versions**
 - Host OS: RedHat 7
 - docker:  18.09.5, build e8ff056
 - docker-compose:1.24.0, build 0aa59064
 - stackstorm/stackstorm image: latest

**To Reproduce**
Donwload repository (I'm not able to clone)
unzip st2-docker-master.zip
cd st2-docker-master/
git init
git commit -m 'Initial Commit' --allow-empty
make env
docker-compose up -d
sudo mkdir -p packs.dev/tutorial/actions
sudo cp tutorial/actions/hello.yaml packs.dev/tutorial/actions
docker-compose exec stackstorm /bin/bash
st2ctl reload --register-all
st2 run tutorial.hello

**Comment by warrenvw** [comment]
Thank you for the detailed steps. Unfortunately, I am unable to reproduce the reported issue.

Does the following thread help?

  https://groups.google.com/forum/#!topic/stackstorm/843w8XJjVFg

**Comment by jalbertodin** [comment]
I was able to solve the problem.
I had setup the ~/.docker/config.json without a noProxy key.
I've just added a exclusion for the localhost and 127.0.0.1 address

**Comment by warrenvw** [comment]
Great! Thanks for letting me know.
