### ISSUE TITLE
Unable to install pack

### ISSUE THREAD

**Issue by jayprakashstar** [StackStorm/st2-docker#178]
**I tried to install pack using command `st2 pack install sensu`  Pack installation failed when it tries to create virtual env**

**Versions**
 - Host OS: CentOS Linux release 7.6.1810
 - docker: Docker version 1.13.1
 - docker-compose: docker-compose version 1.24.0
 - stackstorm/stackstorm image: latest

**To Reproduce**
It is only occurring in given host version on top. I didn't face it on mac
```
git clone git@github.com:stackstorm/st2-docker
cd st2-docker
make env
docker-compose up -d
docker-compose exec stackstorm bash
cd /opt/stackstorm/packs
st2 pack install sensu
```

> Error

{
 “tasks”: [
   {
     “liveaction_id”: “5d02c89c5d8f390060bcffc6”,
     “workflow”: null,
     “created_at”: “2019-06-13T22:05:16.889440+00:00",
     “updated_at”: “2019-06-13T22:05:35.183394+00:00",
     “state”: “succeeded”,
     “result”: {
       “stdout”: “”,
       “result”: {
         “stackstorm_esscache”: “Success.”
       },
       “stderr”: “st2.actions.python.DownloadGitRepoAction: DEBUG    Removing existing pack stackstorm_esscache in /opt/stackstorm/packs/stackstorm_esscache to replace.\nst2.actions.python.DownloadGitRepoAction: DEBUG    Moving pack from /root/8d9059cc72f532ce7b3479cf91893313 to /opt/stackstorm/packs/.\n”,
       “exit_code”: 0
     },
     “id”: “download pack”,
     “execution_id”: “5d02c89c5d8f390060bcffc7”,
     “name”: “download pack”
   },
   {
     “liveaction_id”: “5d02c8af5d8f390060bcffd7”,
     “workflow”: null,
     “created_at”: “2019-06-13T22:05:35.195843+00:00",
     “updated_at”: “2019-06-13T22:05:36.333203+00:00",
     “state”: “succeeded”,
     “result”: {
       “stdout”: “”,
       “result”: [
         “stackstorm_esscache”
       ],
       “stderr”: “”,
       “exit_code”: 0
     },
     “id”: “make a prerun”,
     “execution_id”: “5d02c8af5d8f390060bcffd8",
     “name”: “make a prerun”
   },
   {
     “liveaction_id”: “5d02c8b05d8f390060bcffda”,
     “workflow”: null,
     “created_at”: “2019-06-13T22:05:36.345649+00:00”,
     “updated_at”: “2019-06-13T22:05:41.551981+00:00”,
     “state”: “failed”,
     “result”: {
       “stdout”: “”,
       “result”: “None”,
       “stderr”: “st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Setting up virtualenv for pack \“stackstorm_esscache\” (/opt/stackstorm/packs/stackstorm_esscache)\nst2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Removing virtualenv in \“/opt/stackstorm/virtualenvs/stackstorm_esscache\“\nst2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Creating virtualenv for pack \“stackstorm_esscache\” in \“/opt/stackstorm/virtualenvs/stackstorm_esscache\“\nst2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Creating virtualenv in \“/opt/stackstorm/virtualenvs/stackstorm_esscache\” using Python binary \“/opt/stackstorm/st2/bin/python\“\nst2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Running command \“/opt/stackstorm/st2/bin/virtualenv -p /usr/bin/python3 --always-copy --no-download /opt/stackstorm/virtualenvs/stackstorm_esscache\” to create virtualenv.\nTraceback (most recent call last):\n  File \“/opt/stackstorm/st2/local/lib/python2.7/site-packages/python_runner/python_action_wrapper.py\“, line 334, in <module>\n    obj.run()\n  File \“/opt/stackstorm/st2/local/lib/python2.7/site-packages/python_runner/python_action_wrapper.py\“, line 193, in run\n    output = action.run(**self._parameters)\n  File \“/opt/stackstorm/packs/packs/actions/pack_mgmt/setup_virtualenv.py\“, line 89, in run\n    no_download=no_download)\n  File \“/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/util/virtualenvs.py\“, line 98, in setup_pack_virtualenv\n    use_python3=use_python3, no_download=no_download)\n  File \“/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/util/virtualenvs.py\“, line 210, in create_virtualenv\n    (virtualenv_path, stderr))\nException: Failed to create virtualenv in \“/opt/stackstorm/virtualenvs/stackstorm_esscache\“: \n”,
       “exit_code”: 1
     },
     “id”: “install pack dependencies”,
     “execution_id”: “5d02c8b05d8f390060bcffdb”,
     “name”: “install pack dependencies”
   }
 ],
 “published”: {}
}

**Comment by shusugmt** [comment]
1. Are you really sure that you get the above error/stacktrace when you try to install sensu pack, not the `stackstorm_esscache`?
2. I suspect this part: `DEBUG Running command \“/opt/stackstorm/st2/bin/virtualenv -p /usr/bin/python3 --always-copy --no-download /opt/stackstorm/virtualenvs/stackstorm_esscache\” to create virtualenv.` Why it is using `/usr/bin/python3` which obviously does not exist in the official docker image. (Did you use `st2 pack install --python3`?)

**Comment by jayprakashstar** [comment]
@shusugmt  Yes, I just pasted my pack installation error. But I figured out. The error was related to docker. The storage docker was using in host machine doesn't has execute permission. 
Thanks, I have found the solution so closing it.

**Comment by Sphinxs** [comment]
I have a similar error. The scripts that install the virtual enrivonments are not executed, I have already check all they are in the */st2-docker/st2.d* folder
