### ISSUE TITLE
unable to post image onto Rocketchat through stackstorm

### ISSUE THREAD

**Issue by vageesh7** [StackStorm/st2-docker#179]
unable to post the image onto rocketchat through stackstorm. 

**Versions**
 - Host OS: [Ubuntu 16.04]
 - stackstorm/stackstorm image: [2.6.0]

please specify steps to post image onto Rocketchat.

**Comment by armab** [comment]
Thanks for submitting this issue. StackStorm v2.6.0 is outdated, please update your environment to latest StackStorm.

If you still experience chatops-related issue, please report it to https://github.com/stackstorm/hubot-stackstorm repository dedicated to ChatOps adpters. Please post more detailed more info and steps to reproduce the problem.
