### ISSUE TITLE
mkdir: cannot create directory ‘packs.dev/tutorial’: Permission denied

### ISSUE THREAD

**Issue by gkzz** [StackStorm/st2-docker#180]
**Describe the problem**
I tried to learn how Stackstorm with docker works, as seeing this [tutorial](https://github.com/StackStorm/st2-docker/blob/master/docs/tutorial.md), yet the following error occurred to me.
$ mkdir -p packs.dev/tutorial/actions
```
mkdir: cannot create directory ‘packs.dev/tutorial’: Permission denied
```

**Versions**
 - Host OS: [e.g. Ubuntu 19.04]
 - docker: [19.03.2 (ce)]
 - docker-compose: [1.24.1]
 - stackstorm/stackstorm image: [3.1]

**How I fix this issue**
The cause of the issue is **owner:owner group is root:root**

$ ls -la | grep packs.dev
```
drwxr-xr-x  2 root root  4096 Sep 10 12:26 packs.dev
```

So, I changed owner/owner group form root to general user by executing **chown command**.

$ sudo chown gkz:gkz packs.dev
$ sudo mkdir -p packs.dev/tutorial/actions
$ cp tutorial/actions/hello.yaml packs.dev/tutorial/actions
```
cp: cannot create regular file 'packs.dev/tutorial/actions/hello.yaml': Permission denied
```

$ ls -la packs.dev/
```
total 12
drwxr-xr-x  3 gkz  gkz  4096 Sep 10 12:27 .
drwxr-xr-x 12 gkz  gkz  4096 Sep 10 12:26 ..
drwxr-xr-x  3 root root 4096 Sep 10 12:27 tutorial
```
Don't forget set **-R** option!
$ tree -d packs.dev
```
packs.dev
└── tutorial
    └── actions
2 directories
```
$ sudo chown -R gkz:gkz packs.dev

That's all!!

$ docker-compose exec stackstorm /bin/bash
root@93824703370e:/# ls
```
bin        etc         lib64  proc  srv               tmp
boot       home        media  root  st2-docker        usr
dev        install.sh  mnt    run   st2-manifest.txt  var
dumb-init  lib         opt    sbin  sys
```
root@93824703370e:/# st2ctl reload --register-all
```
Registering content...[flags = --config-file /etc/st2/st2.conf --register-all]
/opt/stackstorm/st2/local/lib/python2.7/site-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a 2.7.x release that supports hmac.compare_digest as soon as possible.
  utils.PersistentlyDeprecated2018,
2019-09-10 03:46:48,496 INFO [-] Connecting to database "st2" @ "mongo:27017" as user "None".
2019-09-10 03:46:48,500 INFO [-] Successfully connected to database "st2" @ "mongo:27017" as user "None".
2019-09-10 03:46:48,804 INFO [-] =========================================================
2019-09-10 03:46:48,804 INFO [-] ############## Registering triggers #####################


.......

st2chatops is not running.
st2timersengine PID: 60
st2workflowengine PID: 52
st2scheduler PID: 54
mistral-server is not running.
mistral.api is not running.
```
root@93824703370e:/# st2 run tutorial.hello
```
.
id: 5d771cbcad384e01561c212c
status: succeeded
parameters: None
result: 
  failed: false
  return_code: 0
  stderr: ''
  stdout: Hello gkz!
  succeeded: true
```
root@93824703370e:/# st2 run tutorial.hello name=Eureka
```
.
id: 5d771ce4ad384e01561c212f
status: succeeded
parameters: 
  name: Eureka
result: 
  failed: false
  return_code: 0
  stderr: ''
  stdout: Hello Eureka!
  succeeded: true
```
root@93824703370e:/# exit
```
exit
```

**Comment by gkzz** [comment]
I know no idea how I close an issue of st2-docker when I found and fix it...

**Comment by gkzz** [comment]
All I have to do is just pull request isn't it??

**Comment by gkzz** [comment]
I modified not docs/tutorial.md but .gitignore, as the following comment was posted.
https://github.com/StackStorm/st2-docker/pull/181#issuecomment-530116353

**Comment by trstruth** [comment]
@gkzz I can't seem to reproduce the perm issue in a fresh st2-docker environment.  It seems like the packs.dev user gets created as me.  Any idea how I can repro this?
