### ISSUE TITLE
ERROR: received unexpected HTTP status: 503 Service Unavailable

### ISSUE THREAD

**Issue by pradiptadas115** [StackStorm/st2-docker#183]
**I am not able to up the docker container**
A clear and concise description of what the problem is.
I have an ubuntu 18.04.3 LTS server machine. Here I am using docker stackstorm. I followed the instruction of downloading docker container ( 
- git clone https://github.com/stackstorm/st2-docker 
- cd st2-docker
- make env
) .now when I am trying to run container up command ( docker-compose up -d ).
I am getting this error: 

> ERROR: received unexpected HTTP status: 503 Service Unavailable

I tried deleting st2-docker folder, rebooting machine and router.
This issue is not fixed.
**VERSION**
 - Host OS: Ubuntu 18.04.3
 - docker: 18.09.7
 - docker-compose: 1.24.1
 - stackstorm/stackstorm image: [e.g. v2.7.1]

**Comment by trstruth** [comment]
The fact that this error is raised when trying to up the containers makes me think that your docker daemon might be improperly configured.

What steps did you follow to install docker and compose?

What is the output of 
* `docker info`
* `docker run hello-world`

**Comment by pradiptadas115** [comment]
Docker info: 
> Containers: 31
>  Running: 0
>  Paused: 0
>  Stopped: 31
> Images: 1
> Server Version: 18.09.7
> Storage Driver: overlay2
>  Backing Filesystem: extfs
>  Supports d_type: true
>  Native Overlay Diff: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins:
>  Volume: local
>  Network: bridge host macvlan null overlay
>  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
> Swarm: inactive
> Runtimes: runc
> Default Runtime: runc
> Init Binary: docker-init
> containerd version:
> runc version: N/A
> init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
> Security Options:
>  apparmor
>  seccomp
>   Profile: default
> Kernel Version: 4.15.0-65-generic
> Operating System: Ubuntu 18.04.3 LTS
> OSType: linux
> Architecture: x86_64
> CPUs: 2
> Total Memory: 1.935GiB
> Name: zombie
> ID: RGLD:RITP:5WR3:CMOD:N76J:LQEN:PJ4Y:H252:SCB2:X4ER:HMMQ:RA7A
> Docker Root Dir: /var/lib/docker
> Debug Mode (client): false
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> Labels:
> Experimental: false
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false
> 
> WARNING: No swap limit support

docker run hello-world

> Hello from Docker!
> This message shows that your installation appears to be working correctly.
> 
> To generate this message, Docker took the following steps:
>  1. The Docker client contacted the Docker daemon.
>  2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
>     (amd64)
>  3. The Docker daemon created a new container from that image which runs the
>     executable that produces the output you are currently reading.
>  4. The Docker daemon streamed that output to the Docker client, which sent it
>     to your terminal.
> 
> To try something more ambitious, you can run an Ubuntu container with:
>  $ docker run -it ubuntu bash
> 
> Share images, automate workflows, and more with a free Docker ID:
>  https://hub.docker.com/
> 
> For more examples and ideas, visit:
>  https://docs.docker.com/get-started/
>

**Comment by pradiptadas115** [comment]
What steps did you follow to install docker and compose?
**docker**:  _sudo apt-get install docker.io_
**docker-compose**:  _sudo curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose_

**Comment by trstruth** [comment]
That all looks fine, I'm trying to pinpoint where that 503 error is coming from - maybe the docker registry itself is returning that?

**Comment by pradiptadas115** [comment]
So what would be my next step ?

**Comment by trstruth** [comment]
Does the error still persist?  A 503 to the docker registry would be transient

**Comment by trstruth** [comment]
The reason I ask is I'm able to follow the steps in the README on my setup and it appears to come up with no problem.  That being said, I already have the  necessary images pulled onto my disk, it appears to be working.  If it's a problem with your docker setup and not with the st2-docker code, the best I can do is try to help you troubleshoot your docker setup.

**Comment by pradiptadas115** [comment]
No it solved don't know how
