### ISSUE TITLE
Pack install fails with error 400

### ISSUE THREAD

**Issue by virtualengineer** [StackStorm/st2-docker#185]
Wanted to try out Stackstorm so I downloaded st2-docker and followed the instructions.
Found the admin/password info and logged in.
However, when I try to install a pack (slack, github etc) it throws an error message.
I tried with the web interface and the cli interface, but got the same message.

ERROR: 400 Client Error: Bad Request
MESSAGE: Action "packs.install" cannot be found. for url: http://127.0.0.1:9101/v1/packs/install

Is this a bug or am I supposed to download each individual pack from Github ?

It seems to be related to a similar issue posted last year in "st2".
https://github.com/StackStorm/st2/issues/4364

![docker_version](https://user-images.githubusercontent.com/49633092/71146013-e9a2f180-2266-11ea-8698-83c72e2332b6.png)
![slack - Packs StackStorm Web UI](https://user-images.githubusercontent.com/49633092/71146019-ec054b80-2266-11ea-908b-b417a456e494.png)
![stackstorm_pack_install_slack_cli](https://user-images.githubusercontent.com/49633092/71146024-edcf0f00-2266-11ea-8bf7-6bc020d02dbf.png)

**Comment by virtualengineer** [comment]
I found an answer!
running the following command in the docker machine in bash made the pack installs work:
st2ctl reload --register-all

reference:
https://github.com/StackStorm/st2/issues/4718

**Comment by armab** [comment]
This is already covered in `st2-docker` Readme: https://github.com/StackStorm/st2-docker#read-first 

The repository is opensource, - feel free to submit a PR to `Readme.md` if you believe there is a better place to make the register content step more visible.

Thanks!
