### ISSUE TITLE
Flask sensor activate but not running

### ISSUE THREAD

**Issue by Sphinxs** [StackStorm/st2-docker#186]
**Problem**

When the virtual environments are created in the `./runtime/st2.d/virtualenv.sh`, they are created asynchronously, which means that the container it's already running and the virtual environments are still in creation.

The script described above causes dependency errors, once a package that has a sensor will load it immediately when the container starts (or at least when the pack is loaded in the container / registered), but the environment it's not created yet, which issue an error that can be seen using the troubleshooting `/opt/stackstorm/st2/bin/st2sensorcontainer --config-file=/etc/st2/st2.conf --debug`: 'the package doesn't has the a virtual environment'.

The core of the problem I'm facing it's that my container is created, then the virtual environments start to being created (in background) and the sensor runs, once the sensor doesn't found the virtual environment an error is issued, then I wait the virtual environments to be created and reload  everything manually, but the Flask application present in my sensor is not loaded, i.e, the sensor is active, but the Flask present in the sensor is not up (I can't make requests to the sensor).

If I run `/opt/stackstorm/st2/bin/st2sensorcontainer --config-file=/etc/st2/st2.conf --debug` after the environments had finish to be create, the Flask application is up and I can do requests to it.

**Versions**
 - Host OS: Mint 19.1
 - Docker: 18.09.7
 - Docker Compose: 1.25.0
 - Stackstorm / Stackstorm image: Stack Storm 7 ST2 3.1.0, image latest

**Reproduce**

Create a sensor that has a [Flask](https://github.com/StackStorm/st2/tree/master/contrib/examples/sensors) application and install the virtual environment of the pack using a script in */runtime/st2.d/script-name.sh*.

**Comment by trstruth** [comment]
Does moving the virtualenv creation script from `/runtime/st2.d` to `/runtime/entrypoint.d` fix this issue?

From the README.md in `/runtime/entrypoint.d`:

>As soon as the stackstorm container is started, and before StackStorm services are started by init, shell scripts with suffix .sh located in this directory are executed in alphanumeric order of the file name.
>Scripts in this directory can be used to write configuration files required by StackStorm.
>NOTE: The scripts must not rely on any StackStorm service being available. If you require StackStorm to be running, then place the scripts in the st2.d directory instead.

Seems as though the scripts in `st2.d` run after the stackstorm services have already started, whereas you want them to run before.

**Comment by Sphinxs** [comment]
> Does moving the virtualenv creation script from `/runtime/st2.d` to `/runtime/entrypoint.d` fix this issue?
> 
> From the README.md in `/runtime/entrypoint.d`:
> 
> > As soon as the stackstorm container is started, and before StackStorm services are started by init, shell scripts with suffix .sh located in this directory are executed in alphanumeric order of the file name.
> > Scripts in this directory can be used to write configuration files required by StackStorm.
> > NOTE: The scripts must not rely on any StackStorm service being available. If you require StackStorm to be running, then place the scripts in the st2.d directory instead.
> 
> Seems as though the scripts in `st2.d` run after the stackstorm services have already started, whereas you want them to run before.

That doesn't work because its necessary to have `st2` loaded to create the environments, e.g, `st2 run packs.setup_virtualenv packs=email`.

I have changed from create the virtual environments to install the packs (which create the virtual environments automatically) `st2 pack install pack-name --python3`, once to use Python 3 at the virtual environments its required to install the packs, instead of copy / create the virtual environments. Besides this each pack needs to be a Git repository, what sucks a fucking lot when you have integrated packs / need to edit 2 or more at the 'same time'!

> I'm not at the company that I was creating the Stack Storm project, I had finished the project and left, I don't know if they have changed something, but when I left I had left the sensor initialization manually in a script inside the `st2.d`
