### ISSUE TITLE
3.2.0 version on https://hub.docker.com/

### ISSUE THREAD

**Issue by Smeds** [StackStorm/st2-docker#199]
Would it be possible that someone make sure that version 3.2.0 can be downloaded from https://hub.docker.com, right now the newest version is 3.1.0

**Comment by armab** [comment]
Hi @Smeds 

https://github.com/StackStorm/st2-docker uses https://github.com/StackStorm/st2-dockerfiles/ Docker images, which have `v3.2.0` image tag deployed to Docker hub. Example: https://hub.docker.com/r/stackstorm/st2actionrunner/tags

I guess you're still using all-in-one Docker image based on Ubuntu Trusty and python2, which was deprecated a while ago and replaced with a new deployment model: https://github.com/StackStorm/st2-docker/pull/192

I'd recommend to update your deployment to most recent `st2-docker` master.
