### ISSUE TITLE
st2chatops missing

### ISSUE THREAD

**Issue by freeyssu** [StackStorm/st2-docker#206]
Hi team.

I believe that st2chatops is the standard package on ST2 but docker-compose.yml does not include st2chatops image and configuration.

Does not have a plan to deploy st2chatops ?

**Comment by armab** [comment]
There is a st2chatops Docker image: https://hub.docker.com/r/stackstorm/st2chatops/ which we build regularly as any other st2 service. Its deployment was codified in K8s/Helm chart (https://github.com/stackstorm/stackstorm-ha#st2chatops), but not in Docker-compose yet.

We'd welcome PR contributions to include st2chatops in the docker-compose configuration. This is a good first issue, should be easy to do and overall very helpful feature.

**Comment by freeyssu** [comment]
@armab, OK I got it :)
I am using the updated "docker-compose.yml" for my environment but it is NOT generic.
So I will have a time to review codes and submit pR.

Thanks.
