### ISSUE TITLE
st2notifier docker image / service doesn't have access to "/etc/st2/keys/datastore_key.json"

### ISSUE THREAD

**Issue by Kami** [StackStorm/st2-docker#211]
It appears ``st2notifier`` image doesn't bundle key which is used for datastore encryption / decryption (``/etc/st2/keys/datastore_key.json`` - I quickly checked and I believe api and action runner service does correctly bundle it).

Notifier needs access to that key since action aliases result templates are rendered that and those templates use Jinja notation which can reference encrypted datastore values.

**Comment by armab** [comment]
Thanks, sounds like a bug.

Should be an easy fix for someone willing to contribute by adding
https://github.com/StackStorm/st2-docker/blob/4e728c26f52b3000735896885720380b3b79d93f/docker-compose.yml#L204

to `st2notifier` docker-compose definition

**Comment by Kami** [comment]
Resolved via #212.
