### ISSUE TITLE
Health check scripts causing issues for authentication with LDAP enabled

### ISSUE THREAD

**Issue by minsis** [StackStorm/st2-docker#220]
**Describe the problem**
Moving a thread from [st2-auth-ldap/issues/92](https://github.com/StackStorm/st2-auth-ldap/issues/92) to here. 

This issue only pertains to when ldap (and probably other methods than default) is enabled. This also applies to rbac if the cached user is not in a proper group. 

Basically what’s happening is when a user has authenticated to the st2client container and an issue arises with the login (failed password check, rbac enabled after first auth, probably other scenarios) the script that checks to see if st2client is functional will run in an endless loop every 5 seconds causing continued failed checks and ultimately locking accounts.   

Right now there are two different checks happening on the container to make sure it’s “healthy”:
One is [scripts/st2client-startup.sh](https://github.com/StackStorm/st2-docker/blob/f925059992a7ab96db414e6873659038ab3a8f6f/scripts/st2client-startup.sh) which is where the failure happens
The other is [scripts/st2web-healthcheck.sh](https://github.com/StackStorm/st2-docker/blob/f925059992a7ab96db414e6873659038ab3a8f6f/scripts/st2web-healthcheck.sh)

Docker runs the web health check which just hits a bunch of api endpoints which don’t require any authentication. This can still be okay and the container shows healthy while the startup script continually fails due to authentication errors with st2 cli commands. 

**Versions**

- Host OS: Oracle 7
- docker: Docker version 17.06.2-ol, build d02b7ab
- docker-compose: [docker-compose version 1.18.0, build 8dd22a9
- stackstorm version: st2 3.4.0dev, on Python 3.6.9. This could be other versions that support other methods of authentication that could fail. 

**To Reproduce**
Enable ldap auth
Using st2client cli authenticate with an ldap user
Enable rbac where the user is unable to execute st2 action list
Restart st2client container. 

**Possible fixes**
Just tossing ideas out for any possible solutions would like to get ideas on this. 
* Run the startup script with a loop cap possibly with longer checks in between. 
* remove this script entirely as it’s sole purpose is just to load packs if none are found. This would only ever happen once I would think. 
    * if removed then move the pack registration to something like bashrc. 
    * if removed add something in motd or read me stating no packs are installed. 
    * since it’s dev maybe this is up to the end user to load packs

**Comment by Kami** [comment]
OK, so it looks like that the st2client startup script is likely indeed causing this issue since it's running every 5 seconds.

I had a look and I don't think st2web should cause it since it doesn't perform actual authentication call, but simply checks that the services return 401 / 401.

For one, if we do decide to keep st2client start up script, I do think we need some kind of hard timeout and abort if it has been reached (and also fail early if we detect RBAC no permissions error or similar).

**Comment by minsis** [comment]
I also want to mention that if you shut off the st2auth container and restart st2client it will work fine as st2 cmd will just ignore authentication if the st2auth is unavailable. 

```bash
root@972b6da4c8aa:/opt/stackstorm# st2 action list
2021-03-04 18:55:28,185  WARNING - Auth API server is not available, skipping authentication.
```

So there needs to be a better way to load packs at start up of the container regardless of authentication failures. Seeing as this ever needs to be done once there's got to be a better solution for dealing with this on a very fresh install.

Another workaround could just be to use something like `st2 --auth-url http://localhost:1234 action list` as the command instead. This way authentication will fail and the startup will continue. This also works for the pack install; if authentication fails, then the packs load anyways.

I think maybe another ticket needs to be opened for the cli client to enforce authentication to begin with as this seems like a security flaw?

**Comment by armab** [comment]
An infinite loop is definitely not good here:
https://github.com/StackStorm/st2-docker/blob/f925059992a7ab96db414e6873659038ab3a8f6f/scripts/st2client-startup.sh#L3-L16

How about trying it for `N` times with exponential backoff and then give up?
