### ISSUE TITLE
Proxy setting

### ISSUE THREAD

**Issue by VladoPortos** [StackStorm/st2-docker#226]
Hello,

I need to go through proxy to reach internet, I have installed succesfully whole StackStorm  in docker. But I can't reach packages for installation. 

In documentation its mentioned to add it to:
_On Ubuntu systems, edit /etc/default/st2actionrunner and /etc/default/st2api to set the proxy configuration environment variables. For RHEL/CentOS systems, edit /etc/sysconfig/st2actionrunner and /etc/sysconfig/st2api._

But where are theses in docker version ? when I try to go inside containers the configs are not there..., any ideas ?

**Comment by armab** [comment]
Proxy settings in Docker might have very different instructions to set it up. There should be something in the Docker documentation about configuring the host environment with proxy.

**Comment by VladoPortos** [comment]
@armab figured it out. True its not stack storm issue but maybe it could be mentioned in documentation. To add two enviroment variables for each container in docker-compose ( for: st2actionrunner and st2api ) 
```
environment:
      HTTP_PROXY: http://<proxy_IP>:<proxy_port>
      HTTPS_PROXY: http://<proxy_IP>:<proxy_port>
```

**Comment by armab** [comment]
@VladoPortos That's a good idea. Sure, please open a PR for the documentation to include the proxy settings :+1:
