### ISSUE TITLE
Bad docker-compose.yml

### ISSUE THREAD

**Issue by rite2hhh** [StackStorm/st2-docker#248]
**Describe the problem**
The `docker-compose.yml` file is invalid which causes the `docker-compose up` command to fail with the following error:
```
$ docker-compose up -d
ERROR: Invalid interpolation format for "environment" option in service "st2chatops": "${HUBOT_SLACK_TOKEN:-}"
```

This happens even when `HUBOT_SLACK_TOKEN` is set in the `.env` file

```
$ cat .env
HUBOT_SLACK_TOKEN=token
```

Appears that the default needs no be a non-empty string in the yml for docker-compose to be able to parse it successfully (not sure if a newer version of docker-compose has a fix for this)

### Potential fix

Adding any random string seems to resolve this issue
```
$ git diff
-      HUBOT_SLACK_TOKEN: ${HUBOT_SLACK_TOKEN:-}
+      HUBOT_SLACK_TOKEN: ${HUBOT_SLACK_TOKEN:-token}
```

**Versions**
 - Host OS:
 ```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
```
 - docker:
 ```
$ docker version
Client:
 Version:           19.03.6
...
Server:
 Engine:
  Version:          19.03.6
 ```
 - docker-compose:
 ```
$ docker-compose version
docker-compose version 1.17.1, build unknown
```
 - stackstorm version: v3.7.0

**To Reproduce**

Simply fork/clone the repo locally and run `docker-compose up -d` (assuming you've completed the prerequisites from [st2-docs]( https://docs.stackstorm.com/install/docker.html))

**Comment by rite2hhh** [comment]
I've put up a simple fix #249

**Comment by armab** [comment]
Works fine in docker-compose `v2.6`.

According to https://docs.docker.com/compose/release-notes/#1170, `docker-compose` version you're using `1.17` is from the old `2017`. I guess it might be a reason for the validation issues you're having. I'm afraid we can't support that old docker-compose version.

Could you update your docker-compose and verify if the `st2-docker` works?

**Comment by rite2hhh** [comment]
In that case, you can actually mark this issue as closed. It's better/safer for me to use up-to-date tools, thanks!

**Comment by armab** [comment]
@rite2hhh Thanks for confirming!
