### ISSUE TITLE
CI build reports success on failed tests

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-docker#251]
See https://github.com/StackStorm/st2-docker/actions/runs/3189178778/jobs/5202693378#step:5:20
where the BATS tests failed, but for some reason, the non-zero exit code is lost somewhere in between.

![Screenshot 2022-10-05 at 11-51-28 Merge pull request #250 from mamercad_github · StackStorm_st2-docker@9609a00](https://user-images.githubusercontent.com/1533818/194044199-ffb57dc6-9177-4eb4-b854-e9259876a9cd.png)

This is a bug and help wanted to fix it.

**Comment by mamercad** [comment]
This is ... interesting (added `echo $?`) right afterwards:

```bash
tests_st2test_1 exited with code 1
0
```

**Comment by mamercad** [comment]
So, I think what's happening is that we need to somehow push the exit code from the `bats` stuff outwards to `docker-compose` (the caller).

**Comment by armab** [comment]
So sounds like `docker-compose up` job is to start the containers which it does successfully, and it doesn't care about the exit codes.

**Comment by mamercad** [comment]
Also, I noticed I missed making the jobs dependent:

```yaml
  docker-compose-up:
    runs-on: ubuntu-latest
    needs: [docker-compose-lint]
```

The "needs" directive.

**Comment by mamercad** [comment]
> `--exit-code-from` Good find!

Hehe, I'm not sure I'm fond of `docker-compose` to be honest:

```
Aborting on container exit...
0
```
