### ISSUE TITLE
feature request: systemd in stackstorm container

### ISSUE THREAD

**Issue by cognifloyd** [StackStorm/st2-docker#29]
I really like the introspective capabilities of systemd. The ability to see which services are running which processes is very convenient. `/etc/init.d/* status` (like say `/etc/init.d/nginx status`) is less informative than systemd's `systemctl` equivalent. I think there are also some synergies on hosts with systemd where `systemctl` can get a container's information without requiring using `docker run/exec/whatever`.

I know can be a big deal to change the underlying image, but what does everyone think about modifying the base container of the stackstorm container so that it uses an OS with systemd? I'm fine with a newer version of debian, or whatever else.

Note: I'm not talking about the mongo or whatever other containers. I don't even know which images/OSes those are using because I haven't needed to enter them yet. If there happens to be a well maintained version of those containers that uses systemd, great. If not, use the well maintained one.

So what does everybody else think?

**Comment by armab** [comment]
`systemd` brings more requirements to the host system, for example cgroup volume passthrough which is a blocker for many systems in terms of security.
So the way to run it is: `docker run --rm -it -v /sys/fs/cgroup:/sys/fs/cgroup image` + `privileged` mode in `docker-compose`.

Additionally, CicleCI prior to 2.0 can't run systemd containers by this reason, see: https://discuss.circleci.com/t/docker-with-centos7-systemd-container/885

So here is why we ran `all-in-one` stackstorm container under the `upstart`, rather then `systemd`. The idea behind the demo container is simplicity and `systemd` didn't fit that.
