### ISSUE TITLE
Add persistent storage + optionally use off-cluster instance of mongo or postgres

### ISSUE THREAD

**Issue by warrenvw** [StackStorm/st2-docker#3]
@emptywee suggests adding persistent storage to mongo and postgres running in the StackStorm cluster.

It should also be possible to use an instance of mongo or postgres running outside the cluster.

Provide a way to set connection strings via environment variables.

**Comment by shusugmt** [comment]
RabbitMQ and redis too. They should be configurable from outside of image. Passing via envvar and modifying those with `crudini` (or sed or awk) within `entrypoint.sh` is one option to achieve this.
