### ISSUE TITLE
Add Chatops or document how to install/configure it

### ISSUE THREAD

**Issue by cognifloyd** [StackStorm/st2-docker#33]
Chatops is not included in these docker images. I didn't realize that until someone mentioned it in slack (iirc). I would like to use chatops eventually.

Please, either include chatops, or, document what it takes to get it installed. A note in the readme saying that it is not included by default (and why) with links to install docs would work for me.

**Comment by Xorso** [comment]
I have created PR 35 to try and help with this. From the discussion in the forums there was talk of keeping different images. I figured this needed to be a new image since there may be others who do not want the chatops installed by default.

**Comment by warrenvw** [comment]
#35 merged. Closing this issue.
