### ISSUE TITLE
Unable to reach auth service.

### ISSUE THREAD

**Issue by johnarnold** [StackStorm/st2-docker#39]
Using the docker containers and docker-compose.

My only change is the stackstorm password in conf/stackstorm.env.  Everything starts up in docker, but I get this error when trying to login to the gui:

"Unable to reach auth service. [auth:true]"

I can docker exec into the stackstorm container and check the logs, but it looks like the auth tokens are being generated and whatnot, there's just some disconnect between the ui and st2auth service ?

Thanks,
John

**Comment by johnarnold** [comment]
Is this expected?  From inside the stackstorm container:

root@a55b4c854bfd:/etc/nginx/conf.d# curl http://127.0.0.1:9100/
{
    "faultstring": "The resource could not be found."
}

**Comment by shusugmt** [comment]
No, that's weird. Can you show some more detail info?

- Host OS and version
- Docker version
- Output of `st2ctl status`
- st2auth log in `/var/log/st2/st2auth.log`

**Comment by johnarnold** [comment]
Ubuntu 16.04

johnar@netdev1-eastus2:~/st2-docker$ docker --version
Docker version 17.05.0-ce, build 89658be

johnar@netdev1-eastus2:~/st2-docker$ docker exec -it stackstorm bash
root@a4edbeb63254:/# st2ctl status
##### st2 components status #####
st2actionrunner PID: 105
st2actionrunner PID: 132
st2actionrunner PID: 178
st2actionrunner PID: 201
st2api PID: 49
st2api PID: 248
st2stream PID: 51
st2stream PID: 249
st2auth PID: 40
st2auth PID: 241
st2garbagecollector PID: 38
st2notifier PID: 44
st2resultstracker PID: 42
st2rulesengine PID: 47
st2sensorcontainer PID: 33
st2chatops is not running.
mistral-server PID: 286
mistral-api PID: 278
mistral-api PID: 308
mistral-api PID: 309

root@a4edbeb63254:/var/log/st2# cat st2auth.log
2017-06-21 17:20:23,001 139812386517872 INFO __init__ [-] Connecting to database "st2" @ "mongo:27017" as user "None".
2017-06-21 17:20:24,310 139812386517872 INFO app [-] st2auth.app app created.
2017-06-21 17:20:40,721 139812321891344 AUDIT access [-] Registered new user "st2admin". (username='st2admin',user={'is_service': False, 'id': '594aaae8f4009800f14d3dfb', 'nicknames': {}, 'name': u'st2admin'})
2017-06-21 17:20:40,723 139812321891344 AUDIT access [-] Access granted to "st2admin" with the token set to expire at "2017-06-22T17:20:40.722481Z". (username='st2admin',token_expiration='2017-06-22T17:20:40.722481Z')

**Comment by johnarnold** [comment]
The one other thing I did change is the port mapping for the stackstorm container.  I changed it from "443:443" to "1443:443" so it doesn't collide with another container.  I doubt that's the issue but I just realized I didn't mention it.

**Comment by shusugmt** [comment]
> I changed it from "443:443" to "1443:443"

@johnarnold That is exactly the reason causing this. By default, st2web expects to be accessed via 443. If you like to change the port, you need to provide custom configuration file and place it at `/opt/stackstorm/static/webui/config.js`

In your case, `config.js` will look like this:
```
'use strict';
angular.module('main')
  .constant('st2Config', {
    hosts: [{
      name: 'default',
      url:  'https://:1443/api',
      auth: 'https://:1443/auth'
    }]
  });
```

In your docker-compose you can mount it like:
```
    volumes:
      - ./config.js:/opt/stackstorm/static/webui/config.js:ro
```

**Comment by johnarnold** [comment]
Ah!  good to know, TIL.   I kicked the other container and moved back to :443, that fixed it.   I'll have to look at templating that file at deploy time if we need to use another port (e.g. behind an auth proxy).

If this is in the docs, my bad.  Didn't pop on a google search.

Thanks!
