### ISSUE TITLE
Outdated Curl Version, Can't use curl with --unix-socket

### ISSUE THREAD

**Issue by nasvillanueva** [StackStorm/st2-docker#44]
I'm trying to make stackstorm [call Docker API via curl](https://docs.docker.com/engine/api/#versioned-api) but the one provided by the base image (ubuntu:trusty) is not updated and [doesn't have any official package](https://packages.ubuntu.com/trusty/curl). On the other hand, ubuntu:xenial has curl [7.47](https://packages.ubuntu.com/xenial/curl) and --unix-socket was introduced in version 7.40

If I can find some time, I'll update the base image from ubuntu:trusty to ubuntu:xenial, test it then submit a PR for this.

**Comment by armab** [comment]
We don't have any plans to make `ubuntu:xenial` as a base container for stackstorm Docker all-in-one version, see https://github.com/StackStorm/st2-docker/issues/29 why.

**Comment by nasvillanueva** [comment]
Oh, Okay then. If that's the case maybe I'll try building curl from source for the container. I'm not sure if it will work though.

**Comment by warrenvw** [comment]
I'll close this issue, but we can re-open in the future if necessary.
