### ISSUE TITLE
Use of SYS_ADMIN

### ISSUE THREAD

**Issue by skjbulcher** [StackStorm/st2-docker#49]
I noticed the following in the `docker-compose.yml` file:

```
    cap_add:
      - SYS_ADMIN
```

`SYS_ADMIN` is [effectively root privileges](https://lwn.net/Articles/486306/) - i.e. if the stackstorm container is compromised, so is the system. Why is `SYS_ADMIN` required?

**Comment by shusugmt** [comment]
Currently it is necessary because upstart running inside the container requires it. 1ppc image can run without it, see: https://github.com/StackStorm/st2-docker/tree/master/runtime/stackstorm-1ppc

**Comment by armab** [comment]
Are you sure that SYS_ADMIN is required for runnning upstart? What limitation/error message do we get without it?

Guessing if it's confused with systemd which requires some more privileges.
