### ISSUE TITLE
Unable to run custom shell scripts in /entrypoint.d

### ISSUE THREAD

**Issue by djh2020** [StackStorm/st2-docker#54]
added this to docker-compose
`- ./entrypoint.d:/entrypoint.d`

added a update_st2conf.sh to the folder
`crudini --set /etc/st2/st2.conf content system_packs_base_path /opt/stackstorm/custom_packs`

made it executable.

The file is present on the container and if I execute it manually it updates the st2.conf.  It doesn't do it when I start the container though

**Comment by warrenvw** [comment]
Does the following alternative command work?

```
  docker run -it -d --privileged \
    -v /path/to/modify-st2-config.sh:/entrypoint.d/modify-st2-config.sh \
      stackstorm/stackstorm:latest
```

**Comment by djh2020** [comment]
@warrenvw  No error, but script does not run.  I can run it manually by connecting to the container, navigating to /entrypoint.d and running the script so it isn't a problem with the volume

**Comment by djh2020** [comment]
Are you trying to achieve something like this?  http://www.camptocamp.com/en/actualite/flexible-docker-entrypoints-scripts/

**Comment by djh2020** [comment]
I blew away all my docker images and pulled new ones.  This fixed the issue.
