### ISSUE TITLE
healthcheck and readiness

### ISSUE THREAD

**Issue by emptywee** [StackStorm/st2-docker#67]
To properly manage lifecycle of all the Stackstorm components in Kubernetes it would be nice to have a way to periodically check health and liveness of them over http or thru a file. 
So far there seems to be no way of doing so, there's no easy way to understand if the running process actually responsive and ready to serve requests.

This is to open a discussion on basically monitoring each component of the Stackstorm platform. Any ideas and input is appreciated.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/ - useful link to understand how Kubernetes can probe running pods for liveness and readiness.

**Comment by armab** [comment]
Superseded by https://github.com/StackStorm/stackstorm-ha/issues/3 and https://github.com/StackStorm/st2/issues/4020

cc @Kami about importance of simplest liveness & readiness probes in K8s.
