### ISSUE TITLE
1ppc: Disable logging to file

### ISSUE THREAD

**Issue by shusugmt** [StackStorm/st2-docker#76]
It is not ideal to output logs to file In 1ppc mode, especially running on Kubernetes. Instead it should log to stdout/stderr **only**.

**Comment by st33v** [comment]
x1000

**Comment by shusugmt** [comment]
1ppc support in this repository is going to be deprecated in favor of https://github.com/StackStorm/stackstorm-ha and https://github.com/StackStorm/st2-dockerfiles
