### ISSUE TITLE
How to install Ansible Integration Pack deps in container?

### ISSUE THREAD

**Issue by anthillmob** [StackStorm/st2-docker#79]
Hi there, the Ansible Integration Pack install needs some [prereqs](https://github.com/StackStorm-Exchange/stackstorm-ansible) i.e. a compiler and krb5 libs which is fine on a local install but how to satisfy this in a running container? Do I need to add to the Dockerfile and rebuild?

Many TIA, Phil

**Comment by anthillmob** [comment]
May have found the solution, hopefully can just add it in as a script:

https://github.com/StackStorm/st2-docker/tree/master/runtime/entrypoint.d

**Comment by warrenvw** [comment]
Hi Phil.

Sorry for the much delayed response. Both options are viable - it really depends on your particular needs.

You could use `entrypoint.d` to satisfy the requirements using an existing image, or you could add to the Dockerfile and rebuild. Obviously, baking everything into the image will result in faster startup times, and provide a more consistent execution if you're starting multiple containers based on the image...

**Comment by warrenvw** [comment]
Please re-open this issue if necessary.

**Comment by vivekrmk** [comment]
Hi, I wish to add the Kafka pack with Stackstorm, is there an example code - where I can see the such an inclusion on entrypoint.sh or are there examples of modified docker files to enable an addition of a pack,  request your help on this, thank!
