### ISSUE TITLE
st2chatops doesn't start

### ISSUE THREAD

**Issue by shusugmt** [StackStorm/st2-docker#86]
README.md says:

> To enable chatops, delete the file /etc/init/st2chatops.override using a script in /st2-docker/entrypoint.d.

```
#!/bin/bash

sudo rm /etc/init/st2chatops.override
```

This doesn't work.

To fix this, we need to use following script instead:

```
#!/bin/bash

# enable st2chatops service
cat << 'EOF' > /etc/init/st2chatops.override
start on runlevel [2345]
stop on runlevel [!2345]
EOF
```

**Comment by warrenvw** [comment]
The fix involves making sure st2chatops is installed before the st2 init config files are updated. This is corrected in #90.
