### ISSUE TITLE
kubernetes 1ppc (one process per container) questions

### ISSUE THREAD

**Issue by elijah** [StackStorm/st2-docker#94]
I've spun up stackstorm using the docker-compose method, and that seems to work.

... but then I decided that I would rather start to future proof myself, so i decided to try doing it with the new kubernetes support in the Edge channel of Docker-Mac.

Differences:  you don't have to use minikube to stand up bits at the beginning.  the kubectl that comes with docker-mac 'just works'. 

Where I get a little fuzzy is on what I should do to replace the 'minikube service st2web --https' command to find the web endpoint -- there's not a minikube in the docker-mac world, and my attempts to dig around with kubectl have revealed what i suspect are correct IPs, but somehow they're not bridged in properly

Note, i'm a k8s n00b so this is complicated stuff to me right now.  

I tried instantiating a new ingress controller - which fails with a mysterious message:

``` kubectl expose deployment st2web --type=LoadBalancer --name=my-service-st2web
The Service "my-service-st2web" is invalid: spec.ports: Invalid value: []api.ServicePort{api.ServicePort{Name:"port-1", Protocol:"TCP", Port:443, TargetPort:intstr.IntOrString{Type:0, IntVal:443, StrVal:""}, NodePort:0}, api.ServicePort{Name:"port-2", Protocol:"UDP", Port:53, TargetPort:intstr.IntOrString{Type:0, IntVal:53, StrVal:""}, NodePort:0}}: cannot create an external load balancer with mix protocols 
```

My st2web deployed bits look like this:

``` 
Name:                     st2web
Namespace:                default
Labels:                   <none>
Annotations:              kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"st2web","namespace":"default"},"spec":{"ports":[{"port":443,"protocol":"TCP"}]...
Selector:                 app=st2web
Type:                     NodePort
IP:                       10.111.133.6
Port:                     <unset>  443/TCP
TargetPort:               443/TCP
NodePort:                 <unset>  30012/TCP
Endpoints:                10.1.0.18:443
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

and my services look like this:

``` 
kubectl get services
NAME                  TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)           AGE
kubernetes            ClusterIP   10.96.0.1        <none>        443/TCP           51m
mistral-api           ClusterIP   10.109.190.26    <none>        8989/TCP          44m
mongo                 ClusterIP   10.99.12.89      <none>        27017/TCP         44m
postgres              ClusterIP   10.111.33.231    <none>        5432/TCP          44m
rabbitmq              ClusterIP   10.99.132.4      <none>        5672/TCP          44m
rabbitmq-management   NodePort    10.108.147.233   <none>        15672:30152/TCP   44m
redis                 ClusterIP   10.105.221.53    <none>        6379/TCP          44m
st2api                ClusterIP   10.102.172.108   <none>        9101/TCP          44m
st2auth               ClusterIP   10.110.236.163   <none>        9100/TCP          44m
st2stream             ClusterIP   10.100.144.187   <none>        9102/TCP          44m
st2web                NodePort    10.111.133.6     <none>        443:30012/TCP     44m
```

Now, I think what I'm missing here is probably an externalip for st2web -- and that things are probably only *slightly*  broken at present.  I'd appreciate someone else's quick glance, and maybe some advice on where to dig in further.  [I've done a **lot** of web proxy work in the past - so I'm confident that it's just my lack of k8s knowledge  blocking me at this point.]

**Comment by elijah** [comment]
A helpful coworker pointed out that there is a NodePort defined, and accesses to localhost:30012 over https get me the st2web ui.

He considered this "cheating" a little bit, but a common hack for what i'm doing - running on a laptop.

**Comment by st33v** [comment]
hey elijah... were you able to get logged in? I'm using the creds in configmaps and I just get 'network error'. I'm using minikube but it should work or not work the same, no?

**Comment by shusugmt** [comment]
Closing this as the original issue is self resolved.
The second one is tracked by #98
