### ISSUE TITLE
ST2API UNABLE TO CONNECT TO NGINX

### ISSUE THREAD

**Issue by SURAJTHEGREAT** [StackStorm/st2-docker#96]
Hi Team,

We could observe the below piece of command in docker-compose.yaml is causing this issue

```
command: [
      "bash", "-c",
      '
       docker-entrypoint.sh
       --requirepass "$$REDIS_PASSWORD"
      '
    ]
```

After removing the above in docker-compose.yaml file , the stackstorm is able to connect to all components.Could you please let us know the significance of the piece of code.

Thanks,
Suraj S

**Comment by warrenvw** [comment]
Sorry for the delay. In short, this snippet enables redis authentication using the specified password. Please see https://github.com/StackStorm/st2-docker/issues/66 for details. Please provide more details (docker version, HEAD SHA of your `st2-docker` workspace, etc.). By any chance, you wouldn't be trying to use an external redis instance?

**Comment by warrenvw** [comment]
Insider your `stackstorm` container, please look at `/etc/st2/st2.conf`. Under `[coordination]`, replace `url = redis://` with `url = redis://:`. If you prefer, you can instead use the following `sed` invocation:

```
sed  -i -e 's/^url = redis:\/\//url = redis:\/\/:/' /etc/st2/st2.conf
```

This issue was resolved in more recent images.
