### ISSUE TITLE
 can't log in to st2web on vanilla kubernetes installation.

### ISSUE THREAD

**Issue by st33v** [StackStorm/st2-docker#98]
I just get 'network error' when logging in through the WEB UI. I've tried using minikube and the kubernetes bundled in docker 'edge' both give the same result. I'm using 'admin/changeme' as specified in configmaps.yml. 

The containers come up fine and I see no errors. This is maybe not a surprise because I don't see any 'errors' in my pods via the dashboard... looks like the st2 processes don't log to stdout/stderr?

**Comment by shusugmt** [comment]
This is regression in 2.6.0. I've just opened [PR to fix this](https://github.com/StackStorm/st2web/pull/493). Until upstream releases a new version, you can try following:

1. Start `minikube` with option `--extra-config=apiserver.ServiceNodePortRange=443-32767` set (I think you need to recreate the cluster)
2. Change the `st2web` service to explicitly specify the `nodePort: 443` to listen the service on port 443

**Comment by st33v** [comment]
Big thanks! I was able to work around this (using k8s bundled with docker - edge) by doing
`sudo kubectl port-forward st2web-76cdd64d57-dgl6f 443:443`
